name: Test

on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.7, 3.0, 3.1, 3.2, 3.3, 3.4, head ]

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - run: bundle exec rake
  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [test]
    steps:
      - name: Dispatch Release
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Generate New Release
          token: ${{ secrets.GITHUB_TOKEN }}
